package com.jumbo.trus;

public enum Flag {
    PLAYER, PLAYER_PLUS, PLAYER_EDIT, PLAYER_DELETE, MATCH, MATCH_PLUS, MATCH_EDIT, MATCH_DELETE, SEASON, SEASON_PLUS, SEASON_EDIT, SEASON_DELETE,
    FINE, FINE_PLUS, FINE_EDIT, FINE_DELETE, BEER, USER, USER_PLUS, USER_EDIT, USER_DELETE, USER_APPROVE, USER_RESET_PASSWORD, USER_ALL
}
